stages:
  load_data:
    cmd: python src/data/load_data.py
    deps:
      - src/data/load_data.py
      - params.yaml
    outs:
      - data/raw/flight_data.csv

  preprocess:
    cmd: python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - params.yaml
      - data/raw/flight_data.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - params.yaml
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/xgb_model.json

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - params.yaml
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models/xgb_model.json
    outs:
      - data/predictions/predictions.csv
